org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=2048m
android.useAndroidX=true
# 关闭新DSL，master版本容易踩坑
android.newDsl=false
org.gradle.parallel=true
org.gradle.caching=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# 关闭AAR元数据校验，解决第三方插件compileSdk版本不匹配报错
android.checkAarMetadata=false
